title: Semih Şenvardar 
logo: "/images/logo.png?raw=true"
description: >
  Computer Science Engineer / Sofware Developer
  <br><br>
  <a href="https://www.linkedin.com/in/semihsenvardar">Go to my linkedin page</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-156095270-1