title: Semih Şenvardar 
logo: "/images/logo.png?raw=true"
description: >
  <br><br>
  { Computer Science Engineer }
  <br><br>
  { Software Development Tech Lead }
  <br><br>
  { Currently working <a href="https://www.hepsiburada.com">@Hepsiburada</a> }
  <br><br>
  <a href="https://www.linkedin.com/in/semihsenvardar">{ Go to linkedin }</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-156095270-1
plugins:
  - jemoji
